version: '3.8'

services:
  # Python Flask Application (Production)
  python-app:
    build:
      context: ./python-app
      target: production
    container_name: python-app-production
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=production
      - PORT=5000
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Node.js Express Application (Production)
  nodejs-app:
    build:
      context: ./nodejs-app
      target: production
    container_name: nodejs-app-production
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=production
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  app-network:
    driver: bridge 