version: '3.8'

services:
  # Python Flask Application
  python-app:
    build:
      context: ./python-app
      target: ${ENVIRONMENT:-development}
    container_name: python-app-${ENVIRONMENT:-development}
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - PORT=5000
      - FLASK_ENV=${ENVIRONMENT:-development}
    volumes:
      - ./python-app:/app
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Node.js Express Application
  nodejs-app:
    build:
      context: ./nodejs-app
      target: ${ENVIRONMENT:-development}
    container_name: nodejs-app-${ENVIRONMENT:-development}
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - PORT=3000
      - NODE_ENV=${ENVIRONMENT:-development}
    volumes:
      - ./nodejs-app:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 